# Generated by Django 4.1.7 on 2023-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elreiprimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('des', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
