# Generated by Django 4.1.7 on 2023-02-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elreiprimo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elreiprimo',
            new_name='Elprimo',
        ),
    ]
